config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'top#index'
  delete 'top/hide/:track_id' => 'top#hide', as: :top_hide

  resources :goods, only: [:index]

  resources :users, only: [:index] do
    get 'playlists'
    get 'playlist/:id' => 'users#playlist', as: :playlist
    get 'playall'
    collection do
      post 'playlist/:id/good_toggle' => 'users#playlist_good_toggle', as: :playlist_good_toggle
    end
  end

  resources :playlists do
    resources :track, only: [:index, :create, :destroy]
    member do
      get  'search'
      get  'search_pager'
      post 'fork'
      get  'tracks'
    end
    collection do
      get 'all'
      get 'recent'
      get 'popular'
    end
  end

  # For OmniAuth
  get "/auth/:provider/callback" => "sessions#callback"
  get "/auth/failure"            => "sessions#failure"
  get "/logout"                  => "sessions#destroy", as: :logout
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :authenticate

  # トップ
  def index
    @tracks       = Track.where(hide_top_flag: false).random_tracks(100)
    @unique_ids   = Track.unique_ids(@tracks, shuffle: true).uniq
    @tracks_hash  = @tracks.index_by{ |x| x.unique_id }
  end

  # トップから非表示にする
  def hide(track_id)
    @track = Track.find_by(id: track_id)
    @track.update!(hide_top_flag: true)

    # redirect_to :root and return
    render layout: false
  end
end

app/views/top/hide.html.haml
= @track.id
= @track.hide_top_flag

app/views/top/index.html.haml
%br
%br

.container{ style: 'width: 1000px; padding: 0 0 0 0;'}
  - if @tracks.present?
    .text-center
      = render partial: '/common/playall', locals: { tracks: @tracks, unique_ids: @unique_ids }
      %br
      - if current_user.blank?
        %br
        %p= link_to "Sign in", "/auth/twitter", class: 'btn btn-primary'
      %br

    %table
      - @unique_ids.each_slice(4) do |ids|
        %tr
        - ids.each do |id|
          - track = @tracks_hash[id]
          %td{ style: 'padding: 5px;', id: "top_track_#{track.id}" }
            = render partial: '/common/video_thumbnail', locals: { track: track }
            - if current_user.present? and current_user.admin_flag
              = link_to "Hide", top_hide_path(track_id: track.id), remote: true, data: { update_target: "top_track_#{track.id}", confirm: "「#{track.id} : #{track.title}」をトップから非表示にします。よろしいですか？", method: 'delete' }, class: 'btn btn-danger btn-xs'
%br