config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'top#index'
  delete 'top/hide/:track_id' => 'top#hide', as: :top_hide

  resources :goods, only: [:index]

  resources :users, only: [:index] do
    get 'playlists'
    get 'playlist/:id' => 'users#playlist', as: :playlist
    get 'playall'
    collection do
      post 'playlist/:id/good_toggle' => 'users#playlist_good_toggle', as: :playlist_good_toggle
    end
  end

  resources :playlists do
    resources :track, only: [:index, :create, :destroy]
    member do
      get  'search'
      get  'search_pager'
      post 'fork'
      get  'tracks'
    end
    collection do
      get 'all'
      get 'recent'
      get 'popular'
    end
  end

  # For OmniAuth
  get "/auth/:provider/callback" => "sessions#callback"
  get "/auth/failure"            => "sessions#failure"
  get "/logout"                  => "sessions#destroy", as: :logout
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  belongs_to :playlist, optional: true
  has_many   :tracks, dependent: :destroy

  scope :mine,   -> (user) { where( playlists: { user_id: user.id } ) }
  scope :active, -> { where('playlists.track_count > 0') }

  validates :name, presence: true

  # プレイリスト所有判定
  def mine?(user)
    return (self.user_id == user.try(:id) ? true : false)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  permits :user, :name, :playlist

  skip_before_action :authenticate, only: [:show, :recent, :popular, :tracks]
  before_action :redirect_public, only: [:show]
  before_action :set_playlist, only: [:show, :edit, :update, :destroy, :search, :search_pager]

  ## プライベート：自分のプレイリストのみ
  def index(search: {})
    @playlists = Playlist.where(user_id: current_user.id).order(created_at: :desc)

    if search.present?
      # @playlists = @playlists.where.like(name: "%#{search[:word]}%")
      @playlists.where!(Playlist.arel_table[:name].matches("%#{search[:word]}%"))
    end

    @playlist  = Playlist.new

    @search = search
  end

  # GET /playlists/1
  def show(id, word: '', page: 1, search: false)
    @tracks     = @playlist.tracks
    @unique_ids = @tracks.pluck(:unique_id)
    @word = word.presence || @playlist.name

    if search.present?
      @videos = Track.youtube_search(@word, @unique_ids, page)
    end
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit(id)
    # @playlist = Playlist.find(id)
  end

  # POST /playlists
  def create(playlist)
    @playlist = Playlist.new(playlist)
    @playlist.user = current_user
    @playlist.save!

    # redirect_to playlists_path and return
    redirect_to playlist_path(@playlist, search: true) and return
  end

  # PUT /playlists/1
  def update(id, playlist)
    # @playlist = Playlist.find(id)

    if @playlist.update(playlist)
      # redirect_to @playlist, notice: 'Playlist was successfully updated.'
      redirect_to playlists_path and return
    else
      render action: 'edit'
    end
  end

  # DELETE /playlists/1
  def destroy(id)
    current_user.playlists.find_by(id: id).destroy

    redirect_to playlists_url
  end

  # Youtube検索
  def search(id, word: '', page: 1)
    unique_ids = @playlist.tracks.mine(current_user).pluck(:unique_id)
    videos = Track.youtube_search(word, unique_ids, page)

    render partial: '/playlists/search_result', locals: { videos: videos, playlist: @playlist, word: word }
  end

  # # Youtube検索オートページャー
  # def search_pager(id, word: '', page: 1)
  #   unique_ids = @playlist.tracks.mine(current_user).pluck(:unique_id)
  #   videos = Track.youtube_search(word, unique_ids, page)

  #   render partial: '/playlists/search_pager', locals: { videos: videos, playlist: @playlist, word: word }
  # end

  # プレイリストプレイオール
  def all(checks: nil)
    checks.permit!
    tracks = Track.mine(current_user)
    tracks.where!(playlist_id: checks.values) if checks.present?
    @tracks = Track.where(id: tracks.pluck(:id).shuffle.first(100))
    @unique_ids   = Track.unique_ids(@tracks, shuffle: true)
    @tracks_hash  = @tracks.index_by{ |x| x.unique_id }
    @checks = checks
  end

  private

  # プレイリスト所有者以外、もしくは未ログインの場合はpublic用URLへ飛ばす
  def redirect_public
    playlist = Playlist.find_by(id: params[:id])

    if playlist.present? and (current_user.blank? or !playlist.mine?(current_user))
      redirect_to tracks_playlist_path(playlist) and return
    end
  end

  # プレイリスト取得
  def set_playlist
    @playlist = Playlist.mine(current_user).includes(:tracks).order("tracks.created_at ASC").find_by(id: params[:id])

    redirect_to playlists_path, alert: "プレイリストが存在しません。" and return if @playlist.blank?
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_add_video.html.haml
-# - if v.present?
-#   .add_videos_margin
-#     .text-center
-#       %iframe{ width: "427", height: "255", src: "https://www.youtube.com/embed/#{v.id}", frameborder: "0", allowfullscreen: true}
-#     %br
-#     -# = "#{v.author.name}"
-#     = "#{Duration.new(v.duration).format('%H:%M:%S')}"
-#     = "#{v.description}"
-#     = "#{v.title}"
-#     = "#{v.id}"
-#     = "#{v.published_at.strftime('%Y/%m/%d %H:%M:%S')}"
-#     = "#{v.favorite_count}"
-#     = "#{v.view_count}"
-#     %br
-#     .text-right
-#       = form_tag playlist_track_index_path(playlist_id: playlist.id, word: word), remote: true, data: { 'update-target' => "add_video_#{v.id}" } do
-#         -# = hidden_field_tag 'video[author_name]', v.author.name
-#         = hidden_field_tag 'video[duration]', v.duration
-#         = hidden_field_tag 'video[description]', v.description
-#         = hidden_field_tag 'video[title]', v.title
-#         = hidden_field_tag 'video[unique_id]', v.id
-#         = hidden_field_tag 'video[published_at]', v.published_at
-#         = hidden_field_tag 'video[favorite_count]', v.favorite_count
-#         = hidden_field_tag 'video[view_count]', v.view_count
-#         = hidden_field_tag 'video[player_url]', v.embed_html
-#         = submit_tag 'Add', data: { disable_with: 'Add' }, class: 'btn btn-primary top_margin_10'
-#     %br
-# - else
-#   - # プレイリストの更新
-#   :javascript
-#     $(function() {
-#       refresh_track_list(#{playlist.id});
-#     });

app/views/playlists/_play_all_area.html.haml
.text-center
  = render partial: '/common/playall', locals: { tracks: tracks, unique_ids: unique_ids }
  %br
  %br
  %p
    = link_to 'Shuffle', playlist_path(playlist, shuffle: true), class: 'btn btn-primary'
    -# = link_to 'Public', tracks_playlist_path(playlist), class: 'btn btn-primary'
  %br

app/views/playlists/_search_pager.html.haml
-# %div{ id: "page_#{videos.current_page}" }
-#   - videos.each do |v|
-#     %span{ id: "add_video_#{v.id}" }
-#       = render partial: '/playlists/add_video', locals: { v: v, playlist: playlist, word: word }

-# - if videos.present? and videos.last_page?
-#   - # リロードボタン
-#   %p.text-center= link_to 'Reload', playlist_path(playlist, search: true), class: 'btn btn-primary'

-#   - # List／ページトップアンカー
-#   %br
-#   .text-right
-#     = link_to 'List', playlists_path, class: 'btn btn-default'
-#     = link_to '↑', '#', class: 'btn btn-default'

app/views/playlists/_search_result.html.haml
-# #search_result_list
-#   - if videos.present?
-#     %h2 Search Result

-#     %p.text-center= link_to 'Reload', playlist_path(playlist, search: true), class: 'btn btn-primary'

-#     %div{ id: "page_#{videos.current_page}" }
-#       - videos.each do |v|
-#         %span{ id: "add_video_#{v.id}" }
-#           = render partial: '/playlists/add_video', locals: { v: v, playlist: playlist, word: word }

-# .text-center
-#   #search_result_area_loading{ style: 'display: none;' }
-#     %br
-#     = image_tag 'loading.gif', width: "48", height: "48"

-# - # オートページャー用パラメータ
-# = hidden_field_tag :autopager_on, true
-# - if videos.present?
-#   = hidden_field_tag :current_page, videos.current_page
-#   -# = hidden_field_tag :num_pages,    videos.num_pages
-#   = hidden_field_tag :num_pages,    7661
-#   = hidden_field_tag :playlist_id,  playlist.id

app/views/playlists/_track_list_area.html.haml
- # Track List
%table
  - tracks_hash = tracks.index_by{ |x| x.unique_id }
  - unique_ids.each_slice(4) do |ids|
    %tr
    - ids.each do |id|
      - track = tracks_hash[id]
      %td{ style: 'padding: 5px;' }
        .gray.track_list_title= track.title
        = render partial: '/common/video_thumbnail', locals: { track: track }
        %div{ style: 'text-align: right; padding: 5px 0px 0px 0px;' }
          = link_to "Delete", playlist_track_path(playlist_id: track.playlist_id, id: track.id), data: { confirm: "「#{track.title}」を削除します。よろしいですか？", method: 'delete', remote: true, update_target: "tracks" }, class: 'btn btn-danger btn-xs'

app/views/playlists/_tracks.html.haml
- # 動画再生
#play_all_area
  - if tracks.present?
    = render partial: '/playlists/play_all_area', locals: { playlist: playlist, tracks: tracks, unique_ids: unique_ids }

- # 再生動画リスト
#track_list_area
  - if tracks.present?
    = render partial: '/playlists/track_list_area', locals: { tracks: tracks, unique_ids: unique_ids }

app/views/playlists/all.html.haml
.container{ style: 'width: 900px'}
  %h3
    Tracks by
    = link_to current_user.name, "#{Settings.twitter_page}#{current_user.name}", target: "_blank"

.container{ style: 'width: 1000px; padding: 0 0 0 0;'}
  - if @tracks.present?
    .text-center
      = render partial: '/common/playall', locals: { tracks: @tracks, unique_ids: @unique_ids }
    %br
    %p.text-center= link_to 'Shuffle', all_playlists_path(checks: @checks), class: 'btn btn-primary'
    %br
    %table
      - @unique_ids.each_slice(4) do |ids|
        %tr
        - ids.each do |id|
          - track = @tracks_hash[id]
          %td{ style: 'padding: 5px;' }
            .track_list_title= link_to_if track.playlist.try(:name).present?, track.playlist.try(:name), playlist_path(track.playlist.id), class: 'gray', target: '_blank'
            = render partial: '/common/video_thumbnail', locals: { track: track }
%br

app/views/playlists/edit.html.haml
.container{ style: 'width: 600px'}
  %br
  %br
  / %h1 プレイリスト編集

  = form_for @playlist do |f|
    = f.text_field :name, class: 'form-control', style: 'width: 400px; float: left;'
    = f.submit 'Update', data: { disable_with: 'Update' }, class: 'btn btn-primary left_margin_10'

  %br

  = link_to 'List', playlists_path, class: 'btn btn-default'

app/views/playlists/index.html.haml
.container{ style: 'width: 700px'}
  %h2 Playlists

  - # プレイリスト追加
  = form_for @playlist do |f|
    = f.text_field :name, class: 'form-control', placeholder: 'Playlist Name', style: 'width: 600px; float: left;'
    = f.submit 'Add', data: { disable_with: 'Add' }, class: 'btn btn-primary left_margin_10'
  %br

  - # プレイリスト検索
  = form_tag playlists_path, method: :get  do |f|
    = text_field_tag 'search[word]', @search[:word], class: 'form-control', placeholder: 'Search Word', style: 'width: 300px; float: left;'
    = submit_tag 'Search', data: { disable_with: 'Search' }, class: 'btn btn-primary left_margin_10'
    = link_to 'Clear', playlists_path, class: 'btn btn-primary left_margin_10'
  %br

  - if @playlists.present?
    = form_tag all_playlists_path, method: 'get' do
      = submit_tag 'Check Play', class: 'btn btn-primary'
      %br
      %br
      / = paginate @playlists, outer_window: 3

      %table.table.table-striped.table-hover{ style: 'width: 700px;'}
        %tr
          %th
            = check_box_tag "all_check", nil, false, id: "all_check"
            = label_tag "all_check", "All"
          %th Thumbnail
          %th Name
          %th Souce
          %th Tracks
          %th

        - @playlists.each.with_index(1) do |playlist, index|
          %tr
            %td{ style: 'text-align: center;' }
              = check_box_tag "checks[#{index}]", playlist.id, false, class: "playlist_check"
              = label_tag "checks_#{index}", "#{index}"
            %td= link_to image_tag(playlist.tracks.first.thumbnail_url, height: 50), tracks_playlist_path(playlist) if playlist.tracks.first.present?
            %td{ nowrap: true, style: 'line-height: 30px;' }
              = link_to playlist.name, playlist_path(playlist)
            %td{ nowrap: true, style: 'line-height: 30px;' }
              - if playlist.playlist.present?
                = link_to playlist.playlist.name, user_playlist_path(playlist.playlist.user_id, playlist.playlist_id)
            %td{ style: 'text-align: right;' }= playlist.track_count
            %td
              = link_to 'Edit', edit_playlist_path(playlist), class: 'btn btn-primary btn-sm'
              = link_to 'Delete', playlist, method: :delete, data: { confirm: "「#{playlist.name}」 is deleted. Are you sure?" }, class: 'btn btn-danger btn-sm'
      = submit_tag 'Check Play', class: 'btn btn-primary'

    / = paginate @playlists, outer_window: 3
%br

app/views/playlists/popular.html.haml
-# .container{ style: 'width: 700px'}
-#   %h2 Popular Playlists

-#   - if @playlists.present?
-#     = paginate @playlists, outer_window: 3

-#     %table.table.table-striped.table-hover{ style: 'width: 700px;'}
-#       %tr
-#         %th No.
-#         %th Thumbnail
-#         %th User
-#         %th Name
-#         %th Souce
-#         %th Views
-#         %th

-#       - @playlists.each.with_index(1) do |playlist, index|
-#         %tr
-#           %td= index + @playlists.offset_value
-#           %td= link_to image_tag(playlist.tracks.first.thumbnail_url, height: 50), tracks_playlist_path(playlist)
-#           %td{ nowrap: true }
-#             = render partial: '/layouts/user_icon', locals: { user: playlist.user, size: "18x18", klass: "margin_minus2" }
-#             = '　'
-#             = link_to playlist.user.name, user_playlists_path(playlist.user) if playlist.user.present?
-#           %td{ nowrap: true, style: 'line-height: 30px;' }
-#             = link_to playlist.name, tracks_playlist_path(playlist)
-#           %td{ nowrap: true, style: 'line-height: 30px;' }
-#             - if playlist.playlist.present?
-#               / = link_to playlist.playlist.name, user_playlist_path(playlist.playlist.user_id, playlist.playlist_id) rescue nil
-#               = link_to playlist.playlist.name, tracks_playlist_path(playlist.playlist_id)
-#           %td= playlist.view_count

-#     = paginate @playlists, outer_window: 3

app/views/playlists/recent.html.haml
-# .container{ style: 'width: 700px'}
-#   %h2 Recent Playlists

-#   - if @playlists.present?
-#     = paginate @playlists, outer_window: 3

-#     %table.table.table-striped.table-hover{ style: 'width: 700px;'}
-#       %tr
-#         %th No.
-#         %th Thumbnail
-#         %th User
-#         %th Name
-#         %th Souce
-#         %th Tracks
-#         %th

-#       - @playlists.each.with_index(1) do |playlist, index|
-#         %tr
-#           %td= index + @playlists.offset_value
-#           %td= link_to image_tag(playlist.tracks.first.thumbnail_url, height: 50), tracks_playlist_path(playlist) if playlist.tracks.first.present?
-#           %td{ nowrap: true }
-#             = render partial: '/layouts/user_icon', locals: { user: playlist.user, size: "18x18", klass: "margin_minus2" }
-#             = '　'
-#             = link_to playlist.user.name, user_playlists_path(playlist.user) if playlist.user.present?
-#           %td{ nowrap: true, style: 'line-height: 30px;' }
-#             = link_to playlist.name, tracks_playlist_path(playlist)
-#           %td{ nowrap: true, style: 'line-height: 30px;' }
-#             - if playlist.playlist.present?
-#               = link_to playlist.playlist.name, tracks_playlist_path(playlist.playlist_id)
-#           %td{ style: 'text-align: center;' }= playlist.track_count

-#     = paginate @playlists, outer_window: 3

app/views/playlists/show.html.haml
- # 作成者用プレイリストページ

- title [Settings.app_name, @playlist.name]
- description @playlist.tracks.first.try(:description)
- keywords @playlist.tracks.pluck(:title)
- set_meta_tags og: { title: [Settings.app_name, @playlist.name].join(' | '), description: @playlist.tracks.first.try(:description), url: request.url, image: @playlist.tracks.first.try(:thumbnail_url) }

- # プレイリスト情報エリア
.container{ style: 'width: 900px'}
  %h2= link_to @playlist.name, playlist_path(@playlist)

  %h4
    Selected by
    = @playlist.user.try(:name)

    - if @playlist.playlist_id.present?
      = ", From"
      = link_to @playlist.playlist.name, user_playlist_path(@playlist.playlist.user_id, @playlist.playlist_id)

    = render partial: '/layouts/amazon_link', locals: { playlist: @playlist }

- # 動画再生エリア
.container{ style: 'width: 1000px; padding: 0 0 0 0;'}
  - # Play All
  #tracks
    = render partial: '/playlists/tracks', locals: { playlist: @playlist, tracks: @tracks, unique_ids: Track.unique_ids(@tracks, shuffle: params[:shuffle]) }
%br
%br

- # Youtube検索
.container{ style: 'width: 700px;' }
  - # 検索フォーム
  -# = form_tag search_playlist_path(id: @playlist.id, word: @word), method: :get, remote: :true, data: { update_target: 'search_result_area' } do
  -#   = text_field_tag :word, @word, { class: 'form-control', style: 'width: 550px; float: left' }
  -#   = submit_tag 'Search', data: { disable_with: 'Search' }, onclick: "$('#search_result_list').empty(); $('#search_result_area_loading').show(); window.history.pushState(null, null, '#{playlist_path(@playlist, search: true)}');", class: 'btn btn-primary left_margin_10'

  = form_tag playlist_path(@playlist.id), method: :get do
    = text_field_tag :word, @word, { class: 'form-control', style: 'width: 550px; float: left' }
    = hidden_field_tag :search, true

    = submit_tag 'Search', data: { disable_with: 'Search' }, class: 'btn btn-primary left_margin_10'

%br

-# - # Youtube検索結果表示エリア
-# .container{ style: 'width: 700px;'}
-#   - # 検索結果
-#   #search_result_area
-#     = render partial: '/playlists/search_result', locals: { videos: @videos, playlist: @playlist, word: @word }

.container{ style: 'width: 700px;'}
  #search_result_area
    #search_result_list
      - if @videos.present?
        %h2 Search Result

        %p.text-center= link_to 'Reload', playlist_path(@playlist, search: true), class: 'btn btn-primary'

        %div
          - @videos.each do |video|
            %span{ id: "add_video_#{video.id}" }
              -# = render partial: '/playlists/add_video', locals: { v: v, playlist: playlist, word: word }
              .add_videos_margin
                .text-center
                  %iframe{ width: "427", height: "255", src: "https://www.youtube.com/embed/#{video.id}", frameborder: "0", allowfullscreen: true}
                %br
                = "#{Duration.new(video.duration).format('%H:%M:%S')}"
                = "#{video.title}"
                = "#{video.published_at&.strftime('%Y/%m/%d %H:%M')}"
                %br
                = "#{video.description}"
                .text-right
                  = form_tag playlist_track_index_path(playlist_id: @playlist.id, video_id: video.id), remote: true, data: { 'update-target' => "add_video_#{video.id}" } do
                    = submit_tag 'Add', data: { disable_with: 'Add' }, class: 'btn btn-primary top_margin_10'
                %br

        %p.text-center= link_to 'Reload', playlist_path(@playlist, search: true), class: 'btn btn-primary'

app/views/playlists/tracks.html.haml
-# - # 公開用プレイリストページ

-# - title [Settings.app_name, @playlist.name]
-# - description @playlist.tracks.first.try(:description)
-# - keywords @playlist.tracks.pluck(:title)
-# - set_meta_tags og: { title: [Settings.app_name, @playlist.name].join(' | '), description: @playlist.tracks.first.try(:description), url: request.url, image: @playlist.tracks.first.try(:thumbnail_url) }

-# .container{ style: 'width: 900px'}
-#   %h2= link_to @playlist.name, playlist_path(@playlist)

-#   %h4
-#     Selected by
-#     = @playlist.user.try(:name)

-#     - if @playlist.playlist_id.present?
-#       = ", From"
-#       = link_to @playlist.playlist.name, tracks_playlist_path(@playlist.playlist_id)

-#     = render partial: '/layouts/amazon_link', locals: { playlist: @playlist }

-#   - # Play All
-#   .text-center
-#     = render partial: '/common/playall', locals: { tracks: @playlist.tracks, unique_ids: @unique_ids }
-#     %br
-#     %br
-#     %p
-#       - if current_user.present?
-#         - # シャッフル
-#         = link_to 'Shuffle', tracks_playlist_path(@playlist, shuffle: true), class: 'btn btn-primary'

-#         - # フォーク
-#         - fork_playlist = Playlist.mine(current_user).find_by(playlist_id: @playlist.id)
-#         - if fork_playlist.present?
-#           - # フォーク済みプレイリストへのリンク
-#           = link_to 'Fork', playlist_path(fork_playlist), class: 'btn btn-primary'
-#         - else
-#           - # フォーク実行
-#           = link_to 'Fork', fork_playlist_path(@playlist), method: :post, class: 'btn btn-primary'
-#       - else
-#         - # ログイン
-#         = link_to 'Sign in', "/auth/twitter", class: 'btn btn-primary'

-#       - # 作成者用プレイリストページへのリンク
-#       - if @playlist.mine?(current_user)
-#         = link_to 'Edit', playlist_path(@playlist), class: 'btn btn-primary'
-#     %br

-# .container{ style: 'width: 1000px; padding: 0 0 0 0;'}
-#   - if @playlist.tracks.present?
-#     - # Track List
-#     %table
-#       - tracks_hash = @playlist.tracks.index_by{ |x| x.unique_id }
-#       - @unique_ids.each_slice(4) do |ids|
-#         %tr
-#         - ids.each do |id|
-#           - track = tracks_hash[id]
-#           %td{ style: 'padding: 5px;' }
-#             %div.gray.track_list_title= track.title
-#             = render partial: '/common/video_thumbnail', locals: { track: track }
-# %br
-# %br