config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'top#index'
  delete 'top/hide/:track_id' => 'top#hide', as: :top_hide

  resources :goods, only: [:index]

  resources :users, only: [:index] do
    get 'playlists'
    get 'playlist/:id' => 'users#playlist', as: :playlist
    get 'playall'
    collection do
      post 'playlist/:id/good_toggle' => 'users#playlist_good_toggle', as: :playlist_good_toggle
    end
  end

  resources :playlists do
    resources :track, only: [:index, :create, :destroy]
    member do
      get  'search'
      get  'search_pager'
      post 'fork'
      get  'tracks'
    end
    collection do
      get 'all'
      get 'recent'
      get 'popular'
    end
  end

  # For OmniAuth
  get "/auth/:provider/callback" => "sessions#callback"
  get "/auth/failure"            => "sessions#failure"
  get "/logout"                  => "sessions#destroy", as: :logout
end

app/views/layouts/_amazon_link.html.haml
= link_to image_tag('amazon.png', width: 63, height: 18), "http://www.amazon.co.jp/s/ref=nb_sb_noss?__mk_ja_JP=カタカナ&url=search-alias%3Daps&field-keywords=#{playlist.name}&at=#{Settings.amazon_affiliate_id}", target: '_blank'

app/views/layouts/_blank.html.haml
- # 動画追加時のエリア消去用

app/views/layouts/_facebook_like_script.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1&appId=<%= Settings.facebook_app_id %>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_user_icon.html.haml
- if user.present?
  = link_to_if user.name.present?, image_tag(user.https_image, size: size, class: klass), "#{Settings[user.last_login_provider + '_page']}#{user.name}", target: "_blank", title: user.name, rel: "tooltip", "data-original-title" => user.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    -# = render partial: '/layouts/google_analytics' if Rails.env.production?
    = display_meta_tags(default_meta_tags)
  %body
    .navbar.navbar-default.navbar-fixed-top
      .navbar-header
        = link_to Settings.app_name, :root, class: 'navbar-brand title_logo'
      .navbar-collapse.collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav
          - if signed_in?
            %li= render partial: '/layouts/user_icon', locals: { user: current_user, size: "18x18", klass: "margin_minus2" }
            %li{ class: (playlists_active?(params) ? 'active' : '') }= link_to "Playlists", playlists_path
            -# %li{ class: (play_all_active?(params) ? 'active' : '') }= link_to "Play all", all_playlists_path
            -# %li{ class: (recent_active?(params) ? 'active' : '') }= link_to "Recent", recent_playlists_path
            -# %li{ class: (popular_active?(params) ? 'active' : '') }= link_to "Popular", popular_playlists_path
            -# %li= link_to "Goods", goods_path
            -# %li= link_to "Users", users_path
            %li= link_to "Logout", logout_path
          - else
            -# %li{ class: (recent_active?(params) ? 'active' : '') }= link_to "Recent", recent_playlists_path
            -# %li{ class: (popular_active?(params) ? 'active' : '') }= link_to "Popular", popular_playlists_path
            -# %li= link_to "Users", users_path
            %li= link_to "Login", "/auth/twitter"
          -# %li= link_to "Feedback", "https://twitter.com/intent/tweet?text=#{URI.encode('#funbox ' + request.url)}", target: '_blank'
    .page_top_margin
      - if flash[:notice].present? or flash[:alert].present?
        %br
        = simple_format(flash[:notice], style: "color: green;") if flash[:notice].present?
        = simple_format(flash[:alert], style: "color: red;")    if flash[:alert].present?
      = yield
    %br/
    %br/
    .text-center
      %br/
      %br
      %p
        Developed by
        %a{ href: "https://github.com/shu0115", target: "_blank" }
          @shu0115
    %br/
    %br/
    %br/